export const countries = [
    { id: "AR", name: "Argentina" },
    { id: "BR", name: "Brasil" },
    { id: "CL", name: "Chile" },
    { id: "CO", name: "Colombia" },
    { id: "MX", name: "México" },
    { id: "US", name: "Estados Unidos" },
    { id: "CA", name: "Canadá" },
    { id: "ES", name: "España" },
    { id: "FR", name: "Francia" },
    { id: "DE", name: "Alemania" },
    { id: "IT", name: "Italia" },
    { id: "GB", name: "Reino Unido" },
    { id: "JP", name: "Japón" },
    { id: "CN", name: "China" },
    { id: "IN", name: "India" },
    { id: "AU", name: "Australia" },
    { id: "RU", name: "Rusia" },
    { id: "ZA", name: "Sudáfrica" },
  ];